/**
 * Removes build outputs and caches so the next build/test starts fresh. Cross-platform
 * (uses node:fs, no rimraf dependency), consistent with the other tsx scripts.
 *
 * Run: npm run clean        # build outputs + tool caches
 *      npm run clean:deep   # also node_modules (follow with `npm ci`)
 *
 * Generated INPUT assets are intentionally kept: the exercise *.bundle files and build/icon.png
 * are regenerated by postinstall (bundles:gen / icon:gen) and are needed at runtime.
 */
import { rmSync, existsSync } from 'node:fs';
import * as path from 'node:path';

const deep = process.argv.includes('--deep');

const targets = [
  'out', // electron-vite build output
  'dist', // electron-builder packaged output
  '.tmp', // transient in-project sandbox dir (if ever created here)
  'node_modules/.vite', // vite dep-optimize cache
  'node_modules/.vitest', // vitest cache
];
if (deep) targets.push('node_modules');

let removed = 0;
for (const t of targets) {
  const p = path.resolve(t);
  if (existsSync(p)) {
    rmSync(p, { recursive: true, force: true });
    console.log(`entfernt: ${t}`);
    removed++;
  }
}
console.log(
  removed === 0
    ? 'Nichts zu entfernen (bereits sauber).'
    : deep
      ? 'Clean (deep) fertig - jetzt `npm ci` ausfuehren.'
      : 'Clean fertig.',
);